version: '3.7'

services:
  mc-server:
    image: itzg/minecraft-server
    environment:
      # see https://github.com/itzg/docker-minecraft-server for configuration details
      - EULA=TRUE
      - VERSION=1.16.4
      - MAX_PLAYERS=2000
      - ONLINE_MODE=false
      - NETWORK_COMPRESSION_THRESHOLD=-1
      - VIEW_DISTANCE=2
      - LEVEL_TYPE=flat
      - DIFFICULTY=peaceful
      - GENERATE_STRUCTURES=false
      - SPAWN_ANIMALS=false
    ports:
      - '25565:25565'
