name: 'Cache build dependencies'
description: 'Cache sbt build dependencies'

inputs:
  cache-version:
    description: 'Cache version (change to invalidate previous caches)'
    required: false
    default: 'v-1'

runs:
  using: "composite"
  steps:
    - name: Prepare build dependencies cache
      uses: actions/cache@v5
      env:
        cache-name: cache-build-dependencies
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.m2
          ~/.cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ inputs.cache-version }}-${{ github.ref }}-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ inputs.cache-version }}-${{ github.ref }}-
          ${{ runner.os }}-build-${{ env.cache-name }}-$${{ inputs.cache-version }}-
