name: Run cached tests

# Build script adopted from itemstack-count-infrastructure
# https://github.com/kory33/itemstack-count-infrastructure/blob/22721250c3e8bb2688538e3933a5f5f998406c2c/.github/workflows/create-release.yml

on:
  push:
    branches:
      - 'master'
      - 'feature/**'
    tags:
      - 'v*'

jobs:
  lint_and_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare build dependencies cache
        uses: ./.github/actions/cache-build-dependencies
        with:
          cache-version: v-4

      - name: Prepare build cache
        uses: ./.github/actions/cache-builds
        with:
          cache-version: v-3

      - name: Lint and Test
        run: sbt "scalafmtCheckAll; compile; scalafixAll --check; test"

  publish:
    runs-on: ubuntu-20.04
    needs: lint_and_test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare build dependencies cache
        uses: ./.github/actions/cache-build-dependencies
        with:
          cache-version: v-3

      - name: Prepare build cache
        uses: ./.github/actions/cache-builds
        with:
          cache-version: v-2

      - name: Import signing PGP key
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
        run: |
          gpg --version
          echo "$PGP_SECRET" | gpg --import

      - name: Publish snapshot artifacts
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        # we need quotation: https://github.community/t/expression-syntax-for-not-startswith/17040
        if: "!startsWith(github.ref, 'refs/tags/v')"
        run: sbt publishSigned

      - name: Publish artifacts to Maven central
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          DECLARED_VERSION=$(cat build.sbt | grep -oP "(?<=ThisBuild / version := \")((\d+\.)+\d+)(?=-SNAPSHOT\")")
          TAGGED_VERSION=$(echo ${{ github.ref }} | sed -e "s~^refs/tags/v~~")

          if [ $DECLARED_VERSION != $TAGGED_VERSION ]; then
            echo "Found $DECLARED_VERSION on build.sbt, but tagged $TAGGED_VERSION. Exiting..."
            exit 1
          fi

          # set the artifact version to DECLARED_VERSION
          sed -i -e "s~ThisBuild / version := \".*\"~ThisBuild / version := \"$DECLARED_VERSION\"~" build.sbt

          # publish to local repository, and then release bundle
          sbt "publishSigned; releaseSonatypeBundle"
