name: Run cached tests

# Build script adopted from itemstack-count-infrastructure (https://github.com/kory33/itemstack-count-infrastructure/blob/22721250c3e8bb2688538e3933a5f5f998406c2c/.github/workflows/create-release.yml)

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'feature/**'
  pull_request:
    branches:
      - 'master'
      - 'develop'

jobs:
  lint_and_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare build dependencies cache
        uses: ./.github/actions/cache-build-dependencies
        with:
          cache-version: v-4

      - name: Prepare build cache
        uses: ./.github/actions/cache-builds
        with:
          cache-version: v-3

      - name: Lint and Test
        run: sbt "scalafmtCheckAll; compile; scalafixAll --check; test"

  publish:
    runs-on: ubuntu-20.04
    needs: lint_and_test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare build dependencies cache
        uses: ./.github/actions/cache-build-dependencies
        with:
          cache-version: v-3

      - name: Prepare build cache
        uses: ./.github/actions/cache-builds
        with:
          cache-version: v-2

      # releasing (possibly snapshot) artifacts
      - name: Import signing PGP key
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
        run: |
          gpg --version
          echo "$PGP_SECRET" | gpg --import

      - name: Publish
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: sbt publishSigned
